---
# Intelligent Gemini CLI Test Playbook
# Verifies installation integrity

- name: Test Intelligent Gemini CLI Installation
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    gemini_home: "{{ ansible_env.HOME }}/.gemini"
    required_dirs:
      - behaviors
      - roles
      - prb-templates
      - commands
      - memory
    required_files:
      - GEMINI.md
      - settings.json
      - .installed
    
  tasks:
    - name: Check installation marker
      stat:
        path: "{{ gemini_home }}/.installed"
      register: install_marker
      failed_when: not install_marker.stat.exists

    - name: Verify directory structure
      stat:
        path: "{{ gemini_home }}/{{ item }}"
      register: dir_check
      failed_when: not dir_check.stat.exists or not dir_check.stat.isdir
      loop: "{{ required_dirs }}"

    - name: Verify required files
      stat:
        path: "{{ gemini_home }}/{{ item }}"
      register: file_check
      failed_when: not file_check.stat.exists
      loop: "{{ required_files }}"

    - name: Check for TOML commands
      find:
        paths: "{{ gemini_home }}/commands"
        patterns: "*.toml"
      register: command_files
      failed_when: command_files.files | length == 0

    - name: Check for behavioral patterns
      find:
        paths: "{{ gemini_home }}/behaviors"
        patterns: "*.md"
      register: behavior_files
      failed_when: behavior_files.files | length == 0

    - name: Check for PRB templates
      find:
        paths: "{{ gemini_home }}/prb-templates"
        patterns: "*.yaml"
      register: template_files
      failed_when: template_files.files | length == 0

    - name: Verify GEMINI.md has proper imports
      lineinfile:
        path: "{{ gemini_home }}/GEMINI.md"
        line: "@~/.gemini/"
        state: present
      check_mode: yes
      register: import_check
      failed_when: import_check.changed

    - name: Display test results
      debug:
        msg:
          - "✅ All tests passed!"
          - "Installation directory: {{ gemini_home }}"
          - "Commands found: {{ command_files.files | length }}"
          - "Behavioral patterns found: {{ behavior_files.files | length }}"
          - "PRB templates found: {{ template_files.files | length }}"